# Generated by Django 6.0.7 on 2026-09-09 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingcustomer",
            name="batch",
            field=models.ForeignKey(
                default="pending",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="customers.batch",
            ),
        ),
    ]
