# Generated by Django 6.0.7 on 2026-09-09 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_pendingcustomer_batch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="status",
        ),
        migrations.AddField(
            model_name="pendingcustomer",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="pendingcustomer",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="customers.batch",
            ),
        ),
    ]
