# Generated by Django 6.0.7 on 2026-09-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_remove_batch_status_pendingcustomer_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
